### PR TITLE
Don't set initial value if element has a property value

### LINKED ISSUE #165: Checkbox CTOR is unaware of possibly already existing "value" property in underlying Element
This is failing test:

```
Element element = new Element("vaadin-checkbox");
        element.setProperty("checked", true);
        UI ui = new UI();
        UI.setCurrent(ui);
        VaadinSession session = Mockito.mock(VaadinSession.class);
        ui.getInternals().setSession(session);
        VaadinService service = Mockito.mock(VaadinService.class);
        Mockito.when(session.getService()).thenReturn(service);

        Instantiator instantiator = Mockito.mock(Instantiator.class);

        Mockito.when(service.getInstantiator()).thenReturn(instantiator);

        Mockito.when(instantiator.createComponent(Checkbox.class))
                .thenAnswer(invocation -> new Checkbox());
        Checkbox field = Component.from(element, Checkbox.class);
        Assert.assertEquals(value, field.getElement().getPropertyRaw("checked"));
```

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #165

### CODE REVIEW

File: vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/GeneratedVaadinCheckbox.java [hunk 1]
```diff
@@ -347,32 +347,63 @@ protected Registration addIndeterminateChangeListener(
             SerializableFunction<T, P> modelToPresentation) {
         super("checked", defaultValue, elementPropertyType, presentationToModel,
                 modelToPresentation);
-        if (initialValue != null) {
-            setModelValue(initialValue, false);
+        if (getElement().getProperty("checked") == null
```
Comment (mshabarov) [inline vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/GeneratedVaadinCheckbox.java:350]: I suppose we don't need `getElement().getProperty("checked") == null` here, because init value is in arguments list and no optional value flag provided

**Review by mshabarov — CHANGES_REQUESTED** [review]

File: vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/GeneratedVaadinCheckbox.java (hunk 1 above)
Comment (denis-anisimov) [reply vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/GeneratedVaadinCheckbox.java:350]: Leftover, thank you.

**Review by mshabarov — APPROVED** [review]
